### ISSUE TITLE
新ミラーの追加

### ISSUE THREAD

**Issue by Fra9ment** [ArchLinuxJP/archweb-jp#15]
2017-09-07の更新で以下の新規ミラーが追加されていたようです。
* https://ftp.jaist.ac.jp/pub/Linux/ArchLinux/$repo/os/$arch
  * 既存ミラーのTLS対応版？
* https://jpn.mirror.pkgbuild.com/$repo/os/$arch

ミラーステータスやらダウンロードやらのページに追加するとミラー選択の参考にしやすそうです。

参考 : [pacman-mirrorlist の git log](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/pacman-mirrorlist&id=19871d68cf6400e8dec92ee50c364beb66f9978c)

**Comment by kusakata** [comment]
情報ありがとうございます。ミラーステータスとダウンロードのページに追加しました。
