### ISSUE TITLE
ArchLinuxJP管轄のミラードメイン

### ISSUE THREAD

**Issue by Fra9ment** [ArchLinuxJP/archweb-jp#16]
この話をするのはまだ先な気もしますが、その場合にはメモ代わりにでも...

新ドメイン移行の作業から、 ArchLinuxJP が管轄するミラーは2種類のドメインでアクセス可能です。
* [mirror.archlinuxjp.org](http://mirror.archlinuxjp.org/) (旧ドメイン)
* [mirror.archlinux.jp](http://mirror.archlinux.jp/) (新ドメイン)

移行の混乱避ける良い方法ですね。

ここで、ドメインが(一時的に?)増えたことで少しだけ問題が発生しており、 [ミラーステータス](https://www.archlinux.jp/mirrors/status/) では旧ドメインのみが表示され、新ドメインの方は載っていないようです。

同様に [ミラー詳細](https://www.archlinux.jp/mirrors/mirror.archlinuxjp.org/) に関しても旧ドメインのみで、新ドメインについてはページが用意されていないようです。

目立った大きな問題ではありませんが、一応お知らせしておきます。

こちらから手を出せそうにないので Issue という形で丸投げになってしまうのが申し訳ないです。

**Comment by kusakata** [comment]
報告ありがとうございます。
ミラーのURLを新ドメインに変更しました。
