### ISSUE TITLE
packageの"Source files"リンクが古いままになっている

### ISSUE THREAD

**Issue by Cj-bc** [ArchLinuxJP/archweb-jp#74]
# 問題
パッケージの情報ページにある `Package Actions/package files` について、現状では [Githubの archlinux/svntogit-packages](https://github.com/archlinux/svntogit-packages)へのリンクとなっていますがarchlinux.orgの方では [gitlab.archlinux.orgへのリンク](https://gitlab.archlinux.org/archlinux/packaging/packages)となっているようです。

![image](https://github.com/ArchLinuxJP/archweb-jp/assets/16875061/23f5d641-6306-48f5-a15d-a3928070d0d9)

[gitへの移行が完了した際のアナウンス](https://archlinux.org/news/git-migration-completed/)にてGitlabへの移行について言及されています。

恐らく
https://github.com/ArchLinuxJP/archweb-jp/blob/41817bab319a3fc6531fe9fb66f761e98e1462ab/views/package.pug#L12-L14

を修正すればよいのだと思うのですが、PRとして提出しても良いでしょうか？
作法が分からなかったため、一度issueとして提出させていただきました。

# 本来どうあってほしいか

- https://gitlab.archlinux.org/archlinux/packaging/packages/ 以下を指してほしい

**Comment by syui** [comment]
ありがとうございます。一応、取り込んでみますが、反映されるかは不明です。

ciなどが設定されていれば反映されるかもしれないので。slackのほうでkusakataさんにmentionしてみます。
